apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-zy71
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-zy71
    app.kubernetes.io/part-of: tkrw-pr712-0075-0020-app
  name: devfile-sample-zy71
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-zy71
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-zy71
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0020-tenant/tkrw-pr712-0075-0020-app/devfile-sample-zy71@sha256:6b1c39d6fb4aa09f40625e8c9fb3b3978ebe92b093f31f7c9bfbc9a765009bd1
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
