apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-zy71
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0020-tenant/tkrw-pr712-0075-0020-app/devfile-sample-zy71@sha256:6b1c39d6fb4aa09f40625e8c9fb3b3978ebe92b093f31f7c9bfbc9a765009bd1
        name: my-nodejs
        resources: {}
status: {}
